//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramaDeRequisas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SITEPLUSEntities2 : DbContext
    {
        public SITEPLUSEntities2()
            : base("name=SITEPLUSEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Almacenes> TBL_Almacenes { get; set; }
        public virtual DbSet<TBL_Centros> TBL_Centros { get; set; }
        public virtual DbSet<TBL_Material> TBL_Material { get; set; }
        public virtual DbSet<TBL_Material_X_Almacen> TBL_Material_X_Almacen { get; set; }
        public virtual DbSet<TBL_Sociedades> TBL_Sociedades { get; set; }
        public virtual DbSet<TBL_Solicitantesfrecuentes> TBL_Solicitantesfrecuentes { get; set; }
        public virtual DbSet<VSP_Sociedades_Centros_Almacenes> VSP_Sociedades_Centros_Almacenes { get; set; }
        public virtual DbSet<TBL_TipoSolicitante> TBL_TipoSolicitante { get; set; }
        public virtual DbSet<TSP_Usuarios> TSP_Usuarios { get; set; }
        public virtual DbSet<TBL_CECO> TBL_CECO { get; set; }
        public virtual DbSet<TBL_Carrito> TBL_Carrito { get; set; }
        public virtual DbSet<TBL_Roles_Uuarios> TBL_Roles_Uuarios { get; set; }
        public virtual DbSet<VSP_usuariosPapeleria> VSP_usuariosPapeleria { get; set; }
        public virtual DbSet<TBL_Estado_Uuarios> TBL_Estado_Uuarios { get; set; }
        public virtual DbSet<TBL_UsuariosSolicitantes> TBL_UsuariosSolicitantes { get; set; }
        public virtual DbSet<TBL_Materiales_Agregados> TBL_Materiales_Agregados { get; set; }
        public virtual DbSet<TBL_RevisionMat_Agregados> TBL_RevisionMat_Agregados { get; set; }
    
        public virtual ObjectResult<string> sp_Insertar_TBL_Materiales_Agregados(string matnr, string maktx, Nullable<int> cantidad, string user)
        {
            var matnrParameter = matnr != null ?
                new ObjectParameter("matnr", matnr) :
                new ObjectParameter("matnr", typeof(string));
    
            var maktxParameter = maktx != null ?
                new ObjectParameter("maktx", maktx) :
                new ObjectParameter("maktx", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Insertar_TBL_Materiales_Agregados", matnrParameter, maktxParameter, cantidadParameter, userParameter);
        }
    }
}
