//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramaDeRequisas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SITEPLUSEntities : DbContext
    {
        public SITEPLUSEntities()
            : base("name=SITEPLUSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Almacenes> TBL_Almacenes { get; set; }
        public virtual DbSet<TBL_Carrito> TBL_Carrito { get; set; }
        public virtual DbSet<TBL_Centros> TBL_Centros { get; set; }
        public virtual DbSet<TBL_Material> TBL_Material { get; set; }
        public virtual DbSet<TBL_Material_X_Almacen> TBL_Material_X_Almacen { get; set; }
        public virtual DbSet<TBL_Requisicion> TBL_Requisicion { get; set; }
        public virtual DbSet<TBL_Sociedades> TBL_Sociedades { get; set; }
        public virtual DbSet<TBL_Solicitantesfrecuentes> TBL_Solicitantesfrecuentes { get; set; }
    }
}
