//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramaDeRequisas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RevisionMat_Agregados
    {
        public int ID_Revision { get; set; }
        public string MATNR { get; set; }
        public string MAKTX { get; set; }
        public Nullable<int> Sociedad { get; set; }
        public Nullable<int> Centro { get; set; }
        public Nullable<int> Ceco { get; set; }
        public Nullable<int> Almacen { get; set; }
        public Nullable<int> Cantidad_Solicitada { get; set; }
        public Nullable<int> Cantidad_Aprobada { get; set; }
        public Nullable<System.DateTime> Fecha_Solicitud { get; set; }
        public Nullable<System.DateTime> Fecha_Cambio_Estado { get; set; }
        public string usuario_Solicitante { get; set; }
        public string Estado { get; set; }
        public string Comentario { get; set; }
    }
}
