//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramaDeRequisas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Materiales_X_Sociedad
    {
        public int ID { get; set; }
        public string Grupo_Articulos { get; set; }
        public Nullable<int> Codigo_material { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> ID_Centro { get; set; }
        public Nullable<int> ID_Almacen { get; set; }
        public string Lote { get; set; }
        public string Lote_Proveedor { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public Nullable<int> Libre_utilizacion { get; set; }
        public Nullable<int> Control_Calidad { get; set; }
        public Nullable<int> Trans_Tras { get; set; }
        public string Valor_Libre_Util { get; set; }
        public string Precio { get; set; }
        public Nullable<int> Pendiente { get; set; }
    
        public virtual TBL_Almacenes TBL_Almacenes { get; set; }
        public virtual TBL_Centros TBL_Centros { get; set; }
    }
}
