//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramaDeRequisas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Sociedades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Sociedades()
        {
            this.TBL_Centros = new HashSet<TBL_Centros>();
            this.TBL_Solicitantesfrecuentes = new HashSet<TBL_Solicitantesfrecuentes>();
            this.TBL_CECO = new HashSet<TBL_CECO>();
            this.TBL_UsuariosSolicitantes = new HashSet<TBL_UsuariosSolicitantes>();
        }
    
        public int ID { get; set; }
        public int Id_Sociedades { get; set; }
        public string NombreSociedad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Centros> TBL_Centros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Solicitantesfrecuentes> TBL_Solicitantesfrecuentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CECO> TBL_CECO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_UsuariosSolicitantes> TBL_UsuariosSolicitantes { get; set; }
    }
}
