//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramaDeRequisas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CECO
    {
        public int ID { get; set; }
        public string ID_CECO { get; set; }
        public Nullable<int> ID_Sociedades { get; set; }
        public string Nombre_CECO { get; set; }
        public string Responsable { get; set; }
    
        public virtual TBL_Sociedades TBL_Sociedades { get; set; }
    }
}
