//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramaDeRequisas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Carrito
    {
        public int ID { get; set; }
        public int Id_Carrito { get; set; }
        public Nullable<int> COD_Material { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cantidad_Pedida { get; set; }
        public string Precio { get; set; }
        public Nullable<int> Cantidad_Aprobada { get; set; }
        public Nullable<int> Cantidad_Disponible { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
