//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramaDeRequisas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UsuariosSolicitantes
    {
        public int ID { get; set; }
        public string nombreSolicitante { get; set; }
        public string pass { get; set; }
        public Nullable<int> ID_Estado { get; set; }
        public Nullable<int> Id_Tipo { get; set; }
        public Nullable<int> Id_Sociedades { get; set; }
        public Nullable<int> ID_Centro { get; set; }
        public Nullable<int> ID_Almacen { get; set; }
        public string ID_CECO { get; set; }
        public Nullable<int> ID_Rol { get; set; }
    
        public virtual TBL_Sociedades TBL_Sociedades { get; set; }
        public virtual TBL_TipoSolicitante TBL_TipoSolicitante { get; set; }
    }
}
