//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramaDeRequisas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Solicitantesfrecuentes
    {
        public int ID { get; set; }
        public int Id_Sociedades { get; set; }
        public string SolicitanteFrecuente1 { get; set; }
        public string SolicitanteFrecuente2 { get; set; }
        public string SolicitanteFrecuente3 { get; set; }
    
        public virtual TBL_Sociedades TBL_Sociedades { get; set; }
    }
}
