//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramaDeRequisas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSP_usuariosPapeleria
    {
        public int ID { get; set; }
        public string nombreSolicitante { get; set; }
        public string pass { get; set; }
        public string Estado { get; set; }
        public string TipoSolicitante { get; set; }
        public string NombreSociedad { get; set; }
        public string NombreCentro { get; set; }
        public int Id_Almacenes { get; set; }
        public string Nombre_CECO { get; set; }
        public string Rol { get; set; }
    }
}
